### ISSUE TITLE
add a dseConfHome variable

### ISSUE THREAD

**Issue by mieslep** [datastax/diagnostic-collection#134] opened 2022-05-26 14:43 UTC
Collector currently hard-codes to look for `conf/dse` files in `/etc/default/dse`, but this can vary by environment.

**Comment by michaelsembwever** [comment] 2022-05-27 06:01
duplicate of https://github.com/datastax/diagnostic-collection/issues/102

**Closed by michaelsembwever** 2022-05-27 06:01 UTC
